### ISSUE TITLE
Exception: No snapshot taken by phantomjs. Please make sure it is installed and available on your path

### ISSUE THREAD

**Issue by xaiomoqing** [pyecharts/pyecharts-snapshot#14]
我已经照着安装了，怎么还有bug？
1.安装了 node.js 环境
2.安装 phantomjs
npm install -g phantomjs-prebuilt
3.安装 pyecharts-snapshot
pip install pyecharts-snapshot
4.引入 pyecharts-snapshot
from pyecharts_snapshot.main import make_a_snapshot
make_a_snapshot('render.html', 'snapshot.png')’

**Comment by chfw** [comment]
render.html能用浏览器打开看到图片吗？

**Comment by xaiomoqing** [comment]
发现问题了
make_a_snapshot('render.html', 'snapshot.png')只能读取、输出在当前文件夹
main.py中MESSAGE_FILE_SAVED_AS = 'File saved in %s/%s'
print(MESSAGE_FILE_SAVED_AS % (os.getcwd(), output_name))
加上地址就不行了
make_a_snapshot('E:/data/render1.html', 'E:/data/snapshot.png')
我觉得可以改一下
# 判断是否加地址,如:E:/data/snapshot.png  dzh
    if len(output_name.split(':')) > 1:
        pass
    else:
        output_name = '%s\%s' % (os.getcwd(), output_name)
print(MESSAGE_FILE_SAVED_AS % (output_name))
