### ISSUE TITLE
用 make_a_snapshot 生成的图片没有显示中文

### ISSUE THREAD

**Issue by chizuo53** [pyecharts/pyecharts-snapshot#17]
![webpage](https://user-images.githubusercontent.com/25220374/37887920-1a429dc6-30f7-11e8-84db-6bd5be5f9488.png)
![snapshot](https://user-images.githubusercontent.com/25220374/37887931-24f1267a-30f7-11e8-91d8-a489b805b727.png)
如图所示，生成的网页有中文但是snapshot之后没有，英文正常显示

**Comment by chfw** [comment]
这个和你的系统的中文字符设置有关。试试 node-echarts, 看是不是也没有中文

**Comment by chizuo53** [comment]
![image](https://user-images.githubusercontent.com/25220374/38078338-86de34da-336e-11e8-8b2c-c8b7a7a888b9.png)
用官网的一个例子通过node_echarts生成的图片，我的语言环境
![image](https://user-images.githubusercontent.com/25220374/38078520-27934528-336f-11e8-9507-effc7a370dad.png)
请问可以通过改语言环境来显示中文吗，因为对python比较熟悉，对nodejs不熟

**Comment by chizuo53** [comment]
找到解决方法了，原因是phantomjs 抓取、截图中文本来就乱码
yum install bitmap-fonts bitmap-fonts-cjk
就解决了
