### ISSUE TITLE
同一个ipynb中，前面的cell利用make_a_snapshot能成功截图，后面开始报错

### ISSUE THREAD

**Issue by February00** [pyecharts/pyecharts-snapshot#20]
我的一个ipynb中，多次利用了make_a_snapshot，前面的十几个图片可以截图成功，到13张图片的时候，就开始报错No phantomjs found in your PATH. Please install it!

An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

我的phantomjs已经安装好了，前面的截图也已经成功了，不知道为什么中途就出问题了

**Comment by chfw** [comment]
哪 phantomjs 没有输出.请查看你的html文件名。而且可以开一个新的ipynb试试第13张图

**Comment by February00** [comment]
html文件名没有问题，我在新开的ipynb中也试过了，可以成功截图，没有问题

**Comment by chfw** [comment]
是手动一个一个运行的 还是用run all cells的菜单命令

**Comment by February00** [comment]
run call cells命令

**Comment by chfw** [comment]
重新 run all cells 的话，一定是第 13 个图吗？

请保留你的ipynb. 等我给你一个改进版的。

**Comment by February00** [comment]
是的，我试了几次，每次都是到第13个图的时候就报错

**Comment by chfw** [comment]
装version 0.1.5试试

`pip install https://github.com/pyecharts/pyecharts-snapshot/archive/master.zip`

**Comment by February00** [comment]
解决了，谢谢

**Comment by chfw** [comment]
最后是什么问题导致的?

**Comment by chfw** [comment]
0.1.5 发布了。估计你发现 0.1.5 没有在 master branch，而是在 dev branch 上。或者就没有用 0.1.5 解决的问题。

**Comment by February00** [comment]
不是利用0.1.5解决的，我怀疑是代码中大量运算造成CPU占用过高导致的。 我优化了一下代码，把部分cell的位置进行了调换，然后就成功了。
