### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zhangjing520** [pyecharts/pyecharts-snapshot#23]
C:\python3\python "1.py" (在目录 C:\Users\85422\Desktop 中)
phantomjs version: 2.1.1
Generating file ...
Traceback (most recent call last):
  File "1.py", line 11, in <module>
    bar.render(path='snapshot.png')
  File "C:\python3\lib\site-packages\pyecharts\base.py", line 132, in render
    **kwargs
  File "C:\python3\lib\site-packages\pyecharts_snapshot\environment.py", line 35, in render_chart_to_file
    make_a_snapshot(tmp_file_path, path, delay=delay, verbose=verbose)
  File "C:\python3\lib\site-packages\pyecharts_snapshot\main.py", line 100, in make_a_snapshot
    raise OSError(content_array)
OSError: ["ReferenceError: Can't find variable: echarts\n\n  undefined:1\nnull\n"]
编译失败。

**Comment by chfw** [comment]
Jupiter-echarts-pypkg is not installed properly. Please reinstall it.

**Comment by Zhangjing520** [comment]
我重新试了安装了。可是不行啊。呜呜

**Comment by Zhangjing520** [comment]
![image](https://user-images.githubusercontent.com/32765269/40635605-6b3f80aa-632d-11e8-8392-825b124c4857.png)

**Comment by Zhangjing520** [comment]
![image](https://user-images.githubusercontent.com/32765269/40635618-7d8d8784-632d-11e8-9b45-616fc86b721e.png)

**Comment by Zhangjing520** [comment]
作者。您好！我其他的方式可以成功。但是您的example不可以。求教！谢谢您了

**Comment by chfw** [comment]
谢谢你反溃问题。请用0.1.7

**Comment by moorejee** [comment]
我遇到了同样的问题，请问这个问题目前最好的解决方案是什么？

**Comment by chfw** [comment]
☝️  pip install pyecharts-snapshot==0.1.7

**Comment by l0o0** [comment]
```python
make_a_snapshot('aaa.html', 'aaa.png')
phantomjs version: 2.1.1

Generating file ...

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-3d5fc6aa8404> in <module>
----> 1 make_a_snapshot('aaa.html', 'aaa.png')

~/.local/lib/python3.5/site-packages/pyecharts_snapshot/main.py in make_a_snapshot(file_name, output_name, delay, pixel_ratio, verbose)
    117         content_array = content.split(",")
    118         if len(content_array) != 2:
--> 119             raise OSError(content_array)
    120         base64_imagedata = content_array[1]
    121         imagedata = decode_base64(base64_imagedata)

OSError: ["ReferenceError: Can't find variable: echarts\n\n  undefined:1\nnull\n"]
```
版本信息
Python 3.5.2 in ubuntu 16.04
pyecharts==0.5.3
pyecharts-javascripthon==0.0.6
pyecharts-jupyter-installer==0.0.3
pyecharts-snapshot==0.1.9

**Comment by chfw** [comment]
echarts.js 没有内嵌在 html 里。

**Comment by chfw** [comment]
能用浏览器打开嘛？

**Comment by l0o0** [comment]
@chfw 你好啊，我那个网页是可以用浏览器打开的。不过我没有在网页源代码里面搜到`echarts.js`这样的字样。不过在源代码里我可以看到有一堆js。
[test.html.zip](https://github.com/pyecharts/pyecharts-snapshot/files/2651322/test.html.zip)

**Comment by zenghk** [comment]
我也遇到这个问题，貌似和html文件的大小有关，相同的代码处理的不同的数据，只有一个大于10M的有问题，其他都可以输出pdf，
win10 python2.7.8
![qq 20190222120117](https://user-images.githubusercontent.com/47877427/53246269-34a5b400-36eb-11e9-94c9-c31e13eaf2b8.png)

**Comment by shexiaobin** [comment]
> 作者。您好！我其他的方式可以成功。但是您的example不可以。求教！谢谢您了

请问您是如何解决的呢？ 可以提供一下代码吗
