### ISSUE TITLE
no legend in the png

### ISSUE THREAD

**Issue by chenlianqing** [pyecharts/pyecharts-snapshot#25]
hello,every friends, I have a problem now, who can help me? thanks very much~
when I create a html  file the legend is intact, but when I use the snapshot to create a png/gif, the title、the lables and the legend are all disappear.
ps: the operating system is Red Hat 4.4.7-16; node version is v10.4.0; phantomjs version is 2.1.1.

**Comment by chfw** [comment]
do you mind sharing your html output?

**Comment by chfw** [comment]
https://github.com/pyecharts/pyecharts/issues/600
