### ISSUE TITLE
Can't get right pdf file.

### ISSUE THREAD

**Issue by gilbert-yuan** [pyecharts/pyecharts-snapshot#26]
I use python2.7.10  run this https://github.com/pyecharts/pyecharts-snapshot/blob/master/examples/pdf.py file , can't get right pdf file, change output file name to *.html ,then can see the right graph. no errors. i installed pyecharts-snapshot, pyecharts and phantomjs. 

how can I get right file? thank your.

**Comment by gilbert-yuan** [comment]
the close issue help https://github.com/pyecharts/pyecharts-snapshot/issues/15 ,my  pyecharts version is too old.

**Comment by chfw** [comment]
OK. good to know. You will need at least pyecharts 0.5.4

**Comment by gilbert-yuan** [comment]
thank you very much.this package is good.
