### ISSUE TITLE
No phantomjs found in your PATH. Please install it!

### ISSUE THREAD

**Issue by killalarm** [pyecharts/pyecharts-snapshot#32]
mac os phantomjs already setup. python3.7

**Comment by chfw** [comment]
type `phantomjs` in your console and see what you get?

**Comment by killalarm** [comment]
phantomjs is hashed (/usr/local/bin/phantomjs)

**Comment by chfw** [comment]
your environment fails this test: https://github.com/pyecharts/pyecharts-snapshot/blob/master/pyecharts_snapshot/main.py#L174

if `phantomjs` is accessible from the same console as you have above, the snapshot lib should find it. 

FYI, I developed this library using macos too. Cannot believe it would go wrong.

**Comment by chfw** [comment]
OK. Try these in your current shell with python enabled:

$ which phantomjs
$ snapshot one-of-your-render.html


Please share the console output with me.

**Comment by killalarm** [comment]
jindeMac-mini:~ jin$ which phantomjs
/usr/local/bin/phantomjs
jindeMac-mini:~ jin$ snapshot one-of-your-render.html
phantomjs version: 2.1.1

Generating file ...
Traceback (most recent call last):
  File "/usr/local/bin/snapshot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pyecharts_snapshot/main.py", line 73, in main
    make_a_snapshot(file_name, output, delay=delay, pixel_ratio=pixel_ratio)
  File "/usr/local/lib/python3.7/site-packages/pyecharts_snapshot/main.py", line 119, in make_a_snapshot
    raise OSError(content_array)
OSError: ["ReferenceError: Can't find variable: echarts\n\n  undefined:1\nnull\n"]

**Comment by chfw** [comment]
This means pyecharts-snapshot works and now if you provide an output of pyecharts, you should see a image output. 

And if you run snapshot's demo scripts in your current shell, you will get image outputs.

**Comment by killalarm** [comment]
current shell  is good
 but use ide shell is fails

**Comment by chfw** [comment]
Please configure your ide to be aware of your env PATH.
