### ISSUE TITLE
能否添加一个函数，直接返回图片base64的编码？

### ISSUE THREAD

**Issue by melin** [pyecharts/pyecharts-snapshot#33]
在分布式场景下，只能直接返回图片，能否添加一个函数，直接返回图片base64的编码？ 最好不要复用render 方法

**Comment by chfw** [comment]
可以。你得自己解码保存起来。

**Comment by chfw** [comment]
已经发布。

如果你对我的改动很满意，可以通过这些个渠道支持我, chfw：http://pyecharts.org/#/zh-cn/donate
