### ISSUE TITLE
默认白色背景，保存成jpeg图片的时候，背景色变成黑色

### ISSUE THREAD

**Issue by edwardzhang0630** [pyecharts/pyecharts-snapshot#35]
描述：
pyecharts将图片保存成jpeg的时候，背景色变成黑色。
保存成png则没有问题，但是图片没有压缩，9M太大了。

版本：
pyecharts 0.5.11
pyecharts-snapshot 0.1.10

图片：
![jp_5y_cci long-short histogram](https://user-images.githubusercontent.com/33045925/51668486-410bf380-1ffd-11e9-875d-badaedc6fe6f.jpeg)

代码：
 bar_image = pyecharts.Bar(”title‘’, width=1200, height=700)
 bar_image.add(‘long’, long_interval_array,
                  long_frequency_array)
 bar_image.add('short', short_interval_array,
                  short_frequency_array)

bar_image.render(path='test.jpeg')

**Comment by liuxian233** [comment]
这是因为转成jpeg是丢失alpha值，可以通过设置背景为非纯白色来规避，比如：
bar_image = pyecharts.Bar(”title‘’, width=1200, height=700, background_color='#eee')

**Comment by edwardzhang0630** [comment]
> 这是因为转成jpeg是丢失alpha值，可以通过设置背景为非纯白色来规避，比如：
> bar_image = pyecharts.Bar(”title‘’, width=1200, height=700, background_color='#eee')

尝试以后，已经解决，jpeg的图片已经变成白色。

个人意见：
我觉得在不设置background_color的时候，html默认是白色背景，png默认也是白色背景，但是jpeg却会变成黑色，应该将白色设置为默认背景色，否则很容易造成误解，而且代码中必须制定背景色为白色，也不是很友好，希望采纳
