### ISSUE TITLE
无法生成png图片

### ISSUE THREAD

**Issue by wuchuting** [pyecharts/pyecharts-snapshot#36]
在issue 23看到跟我同样报错的信息，看到作者提交了commit和终止了问题后
我把作者的回复操作试了一遍
但是发现还是没有成功解决我的 问题
**这是我的错误信息**
phantomjs version: 2.1.1

Generating file ...
Traceback (most recent call last):
  File "E:\学习作业\毕业设计\爬虫\数据分析\output_jinjiang.py", line 10, in <module>
    bar.render(path='snapshot.png', pixel_ratio=3)
  File "D:\Program Files\python\lib\site-packages\pyecharts\base.py", line 146, in render
    **kwargs
  File "D:\Program Files\python\lib\site-packages\pyecharts_snapshot\environment.py", line 35, in render_chart_to_file
    make_a_snapshot(tmp_file_path, path, delay=delay, verbose=verbose)
  File "D:\Program Files\python\lib\site-packages\pyecharts_snapshot\main.py", line 99, in make_a_snapshot
    raise OSError(content_array)
OSError: ["ReferenceError: Can't find variable: echarts\n\n  undefined:1\nnull\n"]
[Finished in 6.0s]

**使用的是有我自己的代码和作者的案例代码，还有尝试了作者说的引擎方式，但都是同样的错误**
无论是这个案例
![r 5pdsi l_saecr_ wl7t s](https://user-images.githubusercontent.com/30004545/53719523-46c8e480-3e99-11e9-9bd4-a160ef4aa9d6.png)
还是这个案例
`from pyecharts import Bar, Line
from pyecharts.engine import create_default_environment

bar = Bar("我的第一个图表", "这里是副标题")
bar.add("服装", ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"], [5, 20, 36, 10, 75, 90])

line = Line("我的第一个图表", "这里是副标题")
line.add("服装", ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"], [5, 20, 36, 10, 75, 90])

env = create_default_environment("html")
# 为渲染创建一个默认配置环境
# create_default_environment(filet_ype)
# file_type: 'html', 'svg', 'png', 'jpeg', 'gif' or 'pdf'

env.render_chart_to_file(bar, path='bar.html')
env.render_chart_to_file(line, path='line.html')`
都是报了同一个错误
我的尝试结果是，如果不用引擎的方式，我可以生成html文件，但是png文件始终无法生成

我的python版本是3.6
使用的是sublime text编辑器
版本信息有
pyecharts==0.5.11
pyecharts-javascripthon==0.0.6
pyecharts-jupyter-installer==0.0.3
pyecharts-snapshot==0.1.7
PyInstaller==3.3.1

以上是我的问题详细内容，跪求作者翻牌，谢谢大佬

**Comment by 97612336** [comment]
> 在issue 23看到跟我同样报错的信息，看到作者提交了commit和终止了问题后
> 我把作者的回复操作试了一遍
> 但是发现还是没有成功解决我的 问题
> **这是我的错误信息**
> phantomjs version: 2.1.1
> 
> Generating file ...
> Traceback (most recent call last):
> File "E:\学习作业\毕业设计\爬虫\数据分析\output_jinjiang.py", line 10, in 
> bar.render(path='snapshot.png', pixel_ratio=3)
> File "D:\Program Files\python\lib\site-packages\pyecharts\base.py", line 146, in render
> **kwargs
> File "D:\Program Files\python\lib\site-packages\pyecharts_snapshot\environment.py", line 35, in render_chart_to_file
> make_a_snapshot(tmp_file_path, path, delay=delay, verbose=verbose)
> File "D:\Program Files\python\lib\site-packages\pyecharts_snapshot\main.py", line 99, in make_a_snapshot
> raise OSError(content_array)
> OSError: ["ReferenceError: Can't find variable: echarts\n\n undefined:1\nnull\n"]
> [Finished in 6.0s]
> 
> **使用的是有我自己的代码和作者的案例代码，还有尝试了作者说的引擎方式，但都是同样的错误**
> 无论是这个案例
> ![r 5pdsi l_saecr_ wl7t s](https://user-images.githubusercontent.com/30004545/53719523-46c8e480-3e99-11e9-9bd4-a160ef4aa9d6.png)
> 还是这个案例
> `from pyecharts import Bar, Line
> from pyecharts.engine import create_default_environment
> 
> bar = Bar("我的第一个图表", "这里是副标题")
> bar.add("服装", ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"], [5, 20, 36, 10, 75, 90])
> 
> line = Line("我的第一个图表", "这里是副标题")
> line.add("服装", ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"], [5, 20, 36, 10, 75, 90])
> 
> env = create_default_environment("html")
> 
> # 为渲染创建一个默认配置环境
> # create_default_environment(filet_ype)
> # file_type: 'html', 'svg', 'png', 'jpeg', 'gif' or 'pdf'
> env.render_chart_to_file(bar, path='bar.html')
> env.render_chart_to_file(line, path='line.html')`
> 都是报了同一个错误
> 我的尝试结果是，如果不用引擎的方式，我可以生成html文件，但是png文件始终无法生成
> 
> 我的python版本是3.6
> 使用的是sublime text编辑器
> 版本信息有
> pyecharts==0.5.11
> pyecharts-javascripthon==0.0.6
> pyecharts-jupyter-installer==0.0.3
> pyecharts-snapshot==0.1.7
> PyInstaller==3.3.1
> 
> 以上是我的问题详细内容，跪求作者翻牌，谢谢大佬

这个问题我也遇到了，我的解决思路是使用echarts-scrappeteer库[https://github.com/chfw/echarts-scrappeteer](url)，然后用Python调用系统命令生成图片。

**Comment by chenjiandongx** [comment]
兄弟使用 pyecharts  V1.0.0 版本吧，关于渲染图片这里有详细介绍

https://pyecharts.org/#/zh-cn/render_images

**Comment by 97612336** [comment]
> 兄弟使用 pyecharts V1.0.0 版本吧，关于渲染图片这里有详细介绍
> 
> https://pyecharts.org/#/zh-cn/render_images

如何安装最新版本的 V 1.0.0 版本？pip 安装的最新版本是V 0.5.11的

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/56866827-8c74da00-6a10-11e9-9f93-1b6a45f31680.png)

**Comment by chfw** [comment]
pyecharts-snapshot 最新版已经不用 phantomjs 了。

**Comment by 97612336** [comment]
谢谢，他正常工作了

**Comment by wuchuting** [comment]
凉了，已经安装1.0.0的，然后使用phantomjs 的时候还是一样报错了，我仔细看了源码。是这句代码 content = engine.make_snapshot(file_name, file_type, delay, pixel_ratio, **kwargs)，主要问题是，为什么会用make_snapshot这个方法的参数来调该方法呢

**Comment by 1015zhc** [comment]
请问你是怎么解决的，我也遇到这个情况了。我的脚本晚上容易出现这种问题，白天重跑正常。

**Comment by wuchuting** [comment]
一直没有解决，作者之前回复我说用最新版本的就可以，但是我还是不行。我怀疑是插件之间的影响，因为用这个插件之前要先安装JS的那个插件。就是这个影响到了。因为单独使用没有问题。

---原始邮件---
发件人: "1015zhc"<notifications@github.com&gt;
发送时间: 2020年4月14日(周二) 上午9:12
收件人: "pyecharts/pyecharts-snapshot"<pyecharts-snapshot@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"wuchuting"<www845812620@qq.com&gt;;
主题: Re: [pyecharts/pyecharts-snapshot] 无法生成png图片 (#36)




 
请问你是怎么解决的，我也遇到这个情况了。我的脚本晚上容易出现这种问题，白天重跑正常。

**Comment by 1015zhc** [comment]
这个问题很奇怪，定位不到原因，群里也没人碰到过。这两天晚上又经常跑失败，有时渲染一两张就报错；有时渲染了七八张才报错。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wuchuting"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 上午9:38
收件人:&nbsp;"pyecharts/pyecharts-snapshot"<pyecharts-snapshot@noreply.github.com&gt;;
抄送:&nbsp;"张红超"<785589225@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts-snapshot] 无法生成png图片 (#36)





 一直没有解决，作者之前回复我说用最新版本的就可以，但是我还是不行。我怀疑是插件之间的影响，因为用这个插件之前要先安装JS的那个插件。就是这个影响到了。因为单独使用没有问题。 
 
 ---原始邮件--- 
 发件人: "1015zhc"<notifications@github.com&amp;gt; 
 发送时间: 2020年4月14日(周二) 上午9:12 
 收件人: "pyecharts/pyecharts-snapshot"<pyecharts-snapshot@noreply.github.com&amp;gt;; 
 抄送: "Author"<author@noreply.github.com&amp;gt;;"wuchuting"<www845812620@qq.com&amp;gt;; 
 主题: Re: [pyecharts/pyecharts-snapshot] 无法生成png图片 (#36) 
 
 
 
 
   
 请问你是怎么解决的，我也遇到这个情况了。我的脚本晚上容易出现这种问题，白天重跑正常。

**Comment by wuchuting** [comment]
我最后是用生成HTML，后面再保存为PNG 的



---原始邮件---
发件人: "1015zhc"<notifications@github.com&gt;
发送时间: 2020年4月14日(周二) 上午9:42
收件人: "pyecharts/pyecharts-snapshot"<pyecharts-snapshot@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"wuchuting"<www845812620@qq.com&gt;;
主题: Re: [pyecharts/pyecharts-snapshot] 无法生成png图片 (#36)




 这个问题很奇怪，定位不到原因，群里也没人碰到过。这两天晚上又经常跑失败，有时渲染一两张就报错；有时渲染了七八张才报错。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"wuchuting"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年4月14日(星期二) 上午9:38 
 收件人:&amp;nbsp;"pyecharts/pyecharts-snapshot"<pyecharts-snapshot@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"张红超"<785589225@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [pyecharts/pyecharts-snapshot] 无法生成png图片 (#36) 
 
 
 
 
 
  一直没有解决，作者之前回复我说用最新版本的就可以，但是我还是不行。我怀疑是插件之间的影响，因为用这个插件之前要先安装JS的那个插件。就是这个影响到了。因为单独使用没有问题。  
   
  ---原始邮件---  
  发件人: "1015zhc"<notifications@github.com&amp;amp;gt;  
  发送时间: 2020年4月14日(周二) 上午9:12  
  收件人: "pyecharts/pyecharts-snapshot"<pyecharts-snapshot@noreply.github.com&amp;amp;gt;;  
  抄送: "Author"<author@noreply.github.com&amp;amp;gt;;"wuchuting"<www845812620@qq.com&amp;amp;gt;;  
  主题: Re: [pyecharts/pyecharts-snapshot] 无法生成png图片 (#36)  
   
   
   
   
     
  请问你是怎么解决的，我也遇到这个情况了。我的脚本晚上容易出现这种问题，白天重跑正常。

**Comment by 1015zhc** [comment]
好的，我试试这个方法。看还会不会出这个问题，谢谢啦


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wuchuting"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 上午9:44
收件人:&nbsp;"pyecharts/pyecharts-snapshot"<pyecharts-snapshot@noreply.github.com&gt;;
抄送:&nbsp;"张红超"<785589225@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts-snapshot] 无法生成png图片 (#36)





 我最后是用生成HTML，后面再保存为PNG 的 
 
 
 
 ---原始邮件--- 
 发件人: "1015zhc"<notifications@github.com&amp;gt; 
 发送时间: 2020年4月14日(周二) 上午9:42 
 收件人: "pyecharts/pyecharts-snapshot"<pyecharts-snapshot@noreply.github.com&amp;gt;; 
 抄送: "Author"<author@noreply.github.com&amp;gt;;"wuchuting"<www845812620@qq.com&amp;gt;; 
 主题: Re: [pyecharts/pyecharts-snapshot] 无法生成png图片 (#36) 
 
 
 
 
  这个问题很奇怪，定位不到原因，群里也没人碰到过。这两天晚上又经常跑失败，有时渲染一两张就报错；有时渲染了七八张才报错。  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"wuchuting"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年4月14日(星期二) 上午9:38  
  收件人:&amp;amp;nbsp;"pyecharts/pyecharts-snapshot"<pyecharts-snapshot@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"张红超"<785589225@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [pyecharts/pyecharts-snapshot] 无法生成png图片 (#36)  
   
   
   
   
   
   一直没有解决，作者之前回复我说用最新版本的就可以，但是我还是不行。我怀疑是插件之间的影响，因为用这个插件之前要先安装JS的那个插件。就是这个影响到了。因为单独使用没有问题。   
     
   ---原始邮件---   
   发件人: "1015zhc"<notifications@github.com&amp;amp;amp;gt;   
   发送时间: 2020年4月14日(周二) 上午9:12   
   收件人: "pyecharts/pyecharts-snapshot"<pyecharts-snapshot@noreply.github.com&amp;amp;amp;gt;;   
   抄送: "Author"<author@noreply.github.com&amp;amp;amp;gt;;"wuchuting"<www845812620@qq.com&amp;amp;amp;gt;;   
   主题: Re: [pyecharts/pyecharts-snapshot] 无法生成png图片 (#36)   
     
     
     
     
       
   请问你是怎么解决的，我也遇到这个情况了。我的脚本晚上容易出现这种问题，白天重跑正常。

**Comment by sigma65535** [comment]
我也遇到这个问题了，通过配置 js_host 参数，使用本地的js静态文件解决了

例如: 
将 https://assets.pyecharts.org/assets/echarts.min.js 下载 放到 ./js/下边
Line(init_opts=InitOpts(js_host="./js/"))

**Comment by Kevenyf** [comment]
> 我也遇到这个问题了，通过配置 js_host 参数，使用本地的js静态文件解决了
> 
> 例如: 将 https://assets.pyecharts.org/assets/echarts.min.js 下载 放到 ./js/下边 Line(init_opts=InitOpts(js_host="./js/"))

这个方法在win系统下好像不管用，依然会报错

**Comment by wuchuting** [comment]
你好，我是吴楚婷，已经收到您的来件，尽快给你回复，谢谢。
