### ISSUE TITLE
OSError: ["ReferenceError: Can't find variable: echarts\n\n  undefined:1\nnull\n"]

### ISSUE THREAD

**Issue by JayHaoran** [pyecharts/pyecharts-snapshot#40]
## 测试代码
```python
from pyecharts import options as opts
from pyecharts.charts import Bar
from pyecharts.render import make_snapshot

from snapshot_phantomjs import snapshot

def bar_chart() -> Bar:
    c = (
        Bar()
        .add_xaxis(["衬衫", "毛衣", "领带", "裤子", "风衣", "高跟鞋", "袜子"])
        .add_yaxis("商家A", [114, 55, 27, 101, 125, 27, 105])
        .add_yaxis("商家B", [57, 134, 137, 129, 145, 60, 49])
        .reversal_axis()
        .set_series_opts(label_opts=opts.LabelOpts(position="right"))
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-测试渲染图片"))
    )
    return c

make_snapshot(snapshot, bar_chart().render(), "bar0.png")
```

## 错误栈
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-77ee97a10cb9> in <module>()
     17     return c
     18 
---> 19 make_snapshot(snapshot, bar_chart().render(), "bar0.png")

~\Program File\Anaconda3\lib\site-packages\pyecharts\render\snapshot.py in make_snapshot(engine, file_name, output_name, delay, pixel_ratio, is_remove_html, **kwargs)
     37         content_array = content.split(",")
     38         if len(content_array) != 2:
---> 39             raise OSError(content_array)
     40 
     41         image_data = decode_base64(content_array[1])

OSError: ["ReferenceError: Can't find variable: echarts\n\n  undefined:1\nnull\n"]

## 版本信息
Python 3.6
pyecharts == 1.5.1
pyecharts-javascripthon==0.0.6
pyecharts-jupyter-installer==0.0.3
pyecharts-snapshot==0.1.7

**Comment by chfw** [comment]
This is known myth. Please use latest version. All these should go hopefully.

**Comment by JayHaoran** [comment]
> 
> 
> This is known myth. Please use latest version. All these should go hopefully.

**Comment by JayHaoran** [comment]
> 
> 
> This is known myth. Please use latest version. All these should go hopefully.

Thank you for your advice, but I do use the latest version(Pyecharts 1.5.1). 
Now I have returned to the previous version(Pyecharts 0.5.11) to temporarily address my needs.

**Comment by chfw** [comment]
Version 0.2.0 uses pypuppeteer.

**Comment by JJJ-ch** [comment]
怎么解决的...
