### ISSUE TITLE
Use pyecharts-snapshot without browser

### ISSUE THREAD

**Issue by LucaNicosia** [pyecharts/pyecharts-snapshot#47]
Hi,
I'm trying to run pyecharts-snapshot inside my WSL2-ubuntu env and for this reason there is no browser. Is there any workaround?

**Comment by chfw** [comment]
then please try older version of pyecharts-snapshot which uses phantomjs.

or if you use latest pyecharts, you can choose https://github.com/pyecharts/snapshot-phantomjs
