### ISSUE TITLE
html转为svg格式后，svg文件打开不是图片，是一段代码

### ISSUE THREAD

**Issue by 51522zzwlwl** [pyecharts/pyecharts-snapshot#48]
# 问题
 您好，我希望利用pyecharts生成svg格式，但转换后的svg文件无法显示图片，请问这个是因为没有加入渲染，还是什么问题嘛

# Code
from pyecharts import options as opts
from pyecharts import render
from pyecharts.charts import Bar
from pyecharts.globals import RenderType
from pyecharts.render import make_snapshot

from snapshot_phantomjs import snapshot
//from snapshot_selenium import snapshot

def bar_chart() -> Bar:
    c = (
        Bar()
        .add_xaxis(["衬衫", "毛衣", "领带", "裤子", "风衣", "高跟鞋", "袜子"])
        .add_yaxis("商家A", [114, 55, 27, 101, 125, 27, 105])
        .add_yaxis("商家B", [57, 134, 137, 129, 145, 60, 49])
        .reversal_axis()
        .set_series_opts(label_opts=opts.LabelOpts(position="right"))
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-测试渲染图片"))
    )
    return c

make_snapshot(snapshot, bar_chart().render(), "bar0.svg")

bar_chart().render('bar0.html')
make_snapshot(snapshot, 'bar0.html', "bar0.svg")

## 命令行
通过命令行 snapshot bar0.html svg 方式获取，同样打开是如下格式

## SVG打开后：
This XML file does not appear to have any style information associated with it. The document tree is shown below.
```
<canvas data-zr-dom-id="zr_0" width="900" height="500" style="position: absolute; left: 0px; top: 0px; width: 900px; height: 500px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"/>
```

**Comment by qtxiaofei** [comment]
请在每个生成的charts对象初始化时，加入svg渲染即可。
之后就可以使用make_snapshot转换文件了
如：
```
Pie(init_opts=opts.InitOpts(
            renderer=RenderType.SVG,
        ))
```
